---
#- debug: msg="hello"

- name: Check if Swarm is enabled
  shell: docker info
  register: docker_info

- name: Init Swarm Mode on swarm-manager1
  shell: docker swarm init --advertise-addr {{ docker_swarm_addr }}
  when: "docker_info.stdout.find('Swarm: active') == -1 and inventory_hostname == groups['nodes'][0]"

#- debug: msg={{ hostvars }}
