---
- name: provision ssh keys
  hosts: all
  remote_user: vagrant
  become: yes
  gather_facts: no
  tasks:
  - name: install ssh key
    authorized_key: user=vagrant 
                    key="{{ lookup('file', '/home/vagrant/.ssh/id_rsa.pub') }}"
                    state=present

- name: Configure Docker Swarm
  hosts: all
  remote_user: vagrant
  become: yes 
  roles:
   - swarm-cluster
